### PR TITLE
add fuck_contributor_covenant to related_projects.md

### PR DESCRIPTION
**Pull request by PragmaTwice**
Emm.. I strongly think **[this project](https://github.com/mengzhuo/fuck_contributor_covenant)** has the same purpose as yours.

### CODE REVIEW

**Comment by binsalem32** [comment]
BusyBox v1.30.1-Stericson (2019-03-17 10:12:06 EDT) multi-call binary.

**Comment by zgoda** [comment]
404

**Comment by mmoll** [comment]
Probably got removed by GH because of newspeak rules.

**Comment by PragmaTwice** [comment]
Well... I'll close the PR.

**Comment by Aspie96** [comment]
Newspeak?

**Pull request closed without merging**
