### PR TITLE
CoC: remove unneccessary ageism from the phrasing

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by david0178418** [comment]
I disagree with this change.  It refers to the ability to self-regulate and posses the resilience that comes with maturation into adulthood.

If someone is not an adult, by exclusion, they are a child that still has some years of maturing (a "young adult" is still an adult).  As a result, they will have to more consciously behave maturely as an adult and do more observation of the example being set by others.

By saying "we are all adults", those _very_ few children who are contributing to open source are given the signal that they are to act maturely (as an adult).

**Comment by actionless** [comment]
idk, i would rather discourage too much adult-ish behavior in my project

but my point was to avoid of regulating that, especially if it's being said in words which require such an explanation to be understood unequivocally

**Comment by actionless** [comment]
also i would elaborate on that from the different point:

imagine someone behaving really "childish" in the worst way you could imagine it. but that person submitting really cool patch which fixes some bug or  implement some needed feature. I won't be so happy accepting that PR since in some weird indirect way it could mean accepting such behavior though i will merge it because i am merging to the project the code, not that person's behavior.

**Comment by domgetter** [comment]
See my comment in #19

**Pull request closed without merging**
